#LIST IS A SET OF DATA OF SAME AND DIFFERENT DATA TYPE 
#LIST IS ALSO MUTABLE

#CREATE A LIST WITH []
a = [1,58,58,48,68]

#PRINT A LIST 
print(a)

#PRINT LIST ELEMENT WITH INDEX
print(a[4])

#WE CANE CHANGE THE ELEMENT ON THE GIVEN INDEX
a[4]=89
print(a)

#WE CAN CREATE A LIST WITH ITEAM OF DIFFERENT DATA TYPE
c = [1,23,2.3,True,"sarthak"]
print(c)
